version: '2'
services:
  db:
    container_name: films-db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASS: '645058001_Bran'
      MYSQL_ROOT_PASSWORD: '645058001_Bran'
    volumes:
      - data:/var/lib/mysql
#  webapp:
#    container_name: films-api
#    build:
#      dockerfile: Dockerfile
#      context: .
#      target: production
#    ports:
#      - 8080:8080
#    expose:
#      - 8080
#    command: npm run start:prod
#    env_file:
#      - .env
#    depends_on:
#      - db
volumes:
  data:
